name: FarmweltPlugin
version: '${project.version}'
main: de.codingtt.farmweltplugin.Main
api-version: '1.16'
author: dervonnebe
description: A powerful farmworld plugin with automatic resets
depend: ['Multiverse-Core']
commands:
    farmwelt:
        aliases:
            - farmworld
        description: Main command for the FarmweltPlugin
        usage: /farmwelt [reset|reload]

permissions:
    farmwelt.use:
        description: Allows access to the farmworld
        default: true
    farmwelt.admin:
        description: Allows resetting the farmworld
        default: op